const globalResources = {
  rollTabName: "roll tab",
  notificationTabName: "notification",
  openRollListTabTitle: "En cours",
  closedRollListTabTitle: "Développés",
  next: "Suivant",
  previous: "Précédent",
  submit: "Envoyer",
  accessPhoneContact: "load contact",
  shootPicture: "shootPicture",
  name: "Nom",
  description: "Description",
  date: "Date",
  participants: "Participants",
  userName: "Nom d'utilisateur",
  password: "Mot de passe",
  confirmPassword: "Confirmation du mot de passe",
  phoneNumber: "Numéro de téléphone",
  logIn: "J'ai déjà un compte",
  signUp: "Je n'ai pas encore de compte",
  remaningPictures: "photos restantes",
  confirm: "confirmer",
  decline: "supprimer",
  invitationText: "vous à invité à rejoindre",
  remainingDays: "jours restants",
  remainingHours: "heures restantes",
  remainingHoursShort: "h",
  remainingDaysShort: "j",
  nameAndDescription: "Nom et description",
  closingDate: "Date de clôture",
  pickDate: "Choisir une date",
  add: "Ajouter",
  required: "Champs obligatoire",
  homeScreen: "Mes pelikos",
  notificationScreen: "Mes invitations",
  rollCreationScreen: "Créer un peliko",
  roll: "Pellicule",
  processingPicture: "Enregistrement de la photo !",
  processingRoll: "Enregistrement de la pellicule !",
  phoneNumberValidityErrorMessage: "Téléphone non valide",
  participantEmptyErrorMessage: "Il manque des participants",
  participantMinimunNumberErrorMessage: "Minimum 1 participant",
  formErrors: "Erreurs dans le formulaire",
  errorNotMatchingPassword: "Les mots de passe ne sont pas identiques",
  emptyRolls: "Pas encore de pellicules",
  emptyNotifications: "Pas d'invitations",
  logOut: "Se déconnecter",
  updateProfile: "Modifier mon profil",
  saveProfile: "Enregistrer mon profil",
  myParameters: "Mes paramètres",
  myProfile: "Mon profil",
  pickProfilePicture: "Choisir une photo",
  cancel: "Annuler",
  baseErrorMessage: "¯|_(ツ)_/¯ Oh no...",
  shotBy: "Capturé par",
  genericError: "generic error",
  connect: "Se connecter",
  subscribe: "S'inscrire",
  search: "Rechercher",
  myParticipants: "Mes participants",
  searchParticipantHelperText:
    "Ajoutez un participant à partir de vos contacts ou d'un numéro de téléphone",
};

export default globalResources;
