const globalResources = {
  rollTabName: "roll tab",
  notificationTabName: "notification",
  openRollListTabTitle: "En cours",
  closedRollListTabTitle: "Développés",
  next: "Suivant",
  previous: "Précédent",
  submit: "submit",
  accessPhoneContact: "load contact",
  shootPicture: "shootPicture",
  name: "Name",
  description: "Description",
  date: "Date",
  participants: "Participants",
  userName: "Nom d'utilisateur",
  password: "Mot de passe",
  confirmPassword: "Confirmation du mot de passe",
  phoneNumber: "Numéro de téléphone",
  signIn: "Change to sign in",
  signUp: "Change to sign up",
  remaningPictures: "photos restantes",
  confirm: "confirm",
  decline: "decline",
  invitationText: "vous à invité à rejoindre",
  remainingDays: "jours restants",
  remainingHours: "heures restantes",
  remainingHoursShort: "h",
  remainingDaysShort: "j",
  nameAndDescription: "Nom et description",
  closingDate: "Date de clôture",
  pickDate: "Choisir une date",
  add: "Ajouter"
};

export default globalResources;
