import * as React from "react";
import { ImageSourcePropType } from "react-native";
import Svg, { Defs, G, Rect, Image, Use, ClipPath } from "react-native-svg";

export interface ThumbnailSvgProps {
  url?: ImageSourcePropType | undefined;
  backgroundColor?: string;
}
const ThumbnailSvg: React.FC<ThumbnailSvgProps> = ({
  url,
  backgroundColor,
  ...props
}) => {
  return (
    <Svg
      width="100%"
      height="156px"
      viewBox="0 0 328 156"
      {...props}
      preserveAspectRatio="none"
    >
      <Defs>
        <Rect id="rect" x="0" y="0" width="100%" height="100%" rx="25" />
        <ClipPath id="clip">
          <Use href="#rect" x="0" y="0" />
          {/* <use xlink:href="#rect"/> */}
        </ClipPath>
      </Defs>
      <G stroke="none" strokeWidth={1} fill="none" fillRule="evenodd">
        <Image
          x={0}
          y={0}
          width="100%"
          height="100%"
          preserveAspectRatio="xMidYMid slice"
          opacity={0.8}
          href={url}
          clipPath="url(#clip)"
          //@ts-ignore
          rx={25}
        />
        <Rect
          fill={backgroundColor}
          x={0}
          y={0}
          width={328}
          height={156}
          rx={25}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={16}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={64}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={40}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={88}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={112}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={136}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={160}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={184}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={208}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={232}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={256}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={280}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.502267264}
          fill="#FFF"
          x={304}
          y={132}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={16}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={64}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={40}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={88}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={112}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={136}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={160}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={184}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={208}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={232}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={256}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={280}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
        <Rect
          fillOpacity={0.50314139}
          fill="#FFF"
          x={304}
          y={16}
          width={6}
          height={8}
          rx={3}
        />
      </G>
    </Svg>
  );
};

export default ThumbnailSvg;
